name: ModePoints
version: 1.2
description: A simple waypoint teleportation plugin.
author: TechnoBulldog
website: http://dev.bukkit.org/server-mods/modepoints/
main: technobulldog.modepoints.ModePoints
permissions:
    modepoints.*:
        description: Gives access to all ModePoints permissions.
        children:
            modepoints.use: true
            modepoints.create: true
    modepoints.use:
        description: Allows the player to use ModePoints.
        default: true
    modepoints.create:
        description: Allows the player to create and destroy waypoints.
        default: true